/*Inserts for 499 products*/
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (1,'Chocolate Sandwich Cookies',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (2,'All-Seasons Salt',104);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (3,'Robust Golden Unsweetened Oolong Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (4,'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (5,'Green Chile Anytime Sauce',5);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (6,'Dry Nose Oil',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (7,'Pure Coconut Water With Orange',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (8,'Cut Russet Potatoes Steam N'' Mash',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (9,'Light Strawberry Blueberry Yogurt',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (10,'Sparkling Orange Juice & Prickly Pear Beverage',115);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (11,'Peach Mango Juice',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (12,'Chocolate Fudge Layer Cake',119);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (13,'Saline Nasal Mist',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (14,'Fresh Scent Dishwasher Cleaner',74);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (15,'Overnight Diapers Size 6',56);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (16,'Mint Chocolate Flavored Syrup',103);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (17,'Rendered Duck Fat',35);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (18,'Pizza for One Suprema  Frozen Pizza',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (19,'Gluten Free Quinoa Three Cheese & Mushroom Blend',63);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (20,'Pomegranate Cranberry & Aloe Vera Enrich Drink',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (21,'Small & Medium Dental Dog Treats',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (22,'Fresh Breath Oral Rinse Mild Mint',20);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (23,'Organic Turkey Burgers',49);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (24,'Tri-Vi-Sol® Vitamins A-C-and D Supplement Drops for Infants',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (25,'Salted Caramel Lean Protein & Fiber Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (26,'Fancy Feast Trout Feast Flaked Wet Cat Food',41);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (27,'Complete Spring Water Foaming Antibacterial Hand Wash',127);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (28,'Wheat Chex Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (29,'Fresh Cut Golden Sweet No Salt Added Whole Kernel Corn',81);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (30,'Three Cheese Ziti, Marinara with Meatballs',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (31,'White Pearl Onions',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (32,'Nacho Cheese White Bean Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (33,'Organic Spaghetti Style Pasta',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (34,'Peanut Butter Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (35,'Italian Herb Porcini Mushrooms Chicken Sausage',106);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (36,'Traditional Lasagna with Meat Sauce Savory Italian Recipes',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (37,'Noodle Soup Mix With Chicken Broth',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (38,'Ultra Antibacterial Dish Liquid',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (39,'Daily Tangerine Citrus Flavored Beverage',64);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (40,'Beef Hot Links Beef Smoked Sausage With Chile Peppers',106);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (41,'Organic Sourdough Einkorn Crackers Rosemary',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (42,'Biotin 1000 mcg',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (43,'Organic Clementines',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (44,'Sparkling Raspberry Seltzer',115);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (45,'European Cucumber',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (46,'Raisin Cinnamon Bagels 5 count',58);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (47,'Onion Flavor Organic Roasted Seaweed Snack',66);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (48,'School Glue, Washable, No Run',87);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (49,'Vegetarian Grain Meat Sausages Italian - 4 CT',14);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (50,'Pumpkin Muffin Mix',105);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (51,'Sa Extra Hold Mousse Hair Styling',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (52,'Mirabelle Brut Rose',134);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (53,'Whole Leaf Pure Aloe With Lemon Juice',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (54,'24/7 Performance Cat Litter',41);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (55,'Lasting Color Shampoo',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (56,'Healthy Pop Butter Popcorn',23);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (57,'Flat Toothpicks',111);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (58,'Whole Wheat Tortillas',128);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (59,'Medium Taqueria Style Chipotle Salsa',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (60,'Cheesy Creations Roasted Garlic Parmesan Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (61,'Ramen Noodles Soup Chicken Mushroom Flavor',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (62,'Premium Deli Oven Roasted Turkey Breast',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (63,'Banana & Sweet Potato Organic Teething Wafers',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (64,'Autumn Vegetable & Turkey Dinner with Lil'' Bits Purees Dinner',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (65,'Organic Red Wine & Olive Oil Dressing Organic',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (66,'European Style Spring Mix',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (67,'Jelly, Blackberry',88);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (68,'Pancake Mix, Buttermilk',130);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (69,'Vanilla with Almond Milk Iced Coffee',26);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (70,'Sweet Cooking Rice Seasoning',66);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (71,'Ultra 7 Inch Polypropylene Traditional Plates',111);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (72,'Organic Honeycrisp Apples',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (73,'Jasmine Tea Unfiltered Ginger Ale',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (74,'Artisan Chick''n & Apple Sausage',14);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (75,'Hemp Protein, Organic',65);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (76,'Spinach Basil Garlic Linguini',12);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (77,'Coconut Chocolate Chip Energy Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (78,'Nutter Butter Cookie Bites Go-Pak',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (79,'Wild Albacore Tuna No Salt Added',95);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (80,'French  Tarragon Wine Vinegar',19);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (81,'Blakes Chicken Parmesan Dinner',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (82,'All Natural 100% Apple Juice',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (83,'100% Whole Wheat Pita Bread',128);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (84,'Lamb Shank',7);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (85,'Soppressata Piccante',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (86,'Camilia, Single Liquid Doses',6);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (87,'Classics Earl Grey Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (88,'Probiotics High Potency Capsules',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (89,'Yogurt Fruit Dip Sliced Apples',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (90,'Smorz Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (91,'Kind Prenatal Once Daily',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (92,'Meat In The Middle Large Rawhide Chews',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (93,'Uncured Cracked Pepper Beef',23);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (94,'Organic Blueberry Blitz Fruit & Veggie Smoothie Mashups',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (95,'Organic Rice Vinegar',66);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (96,'Sprinklez Confetti Fun Organic Toppings',97);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (97,'Organic Chamomile Lemon Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (98,'2% Yellow American Cheese',2);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (99,'Local Living Butter Lettuce',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (100,'Peanut Butter & Strawberry Jam Sandwich',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (101,'Bread, Healthy Whole Grain',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (102,'Danish Butter Cookies',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (103,'Sprouted Kale Cracker',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (104,'High Fiber Tomato Basil Soup',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (105,'Easy Grab 9\"x13\" Oblong Glass Bakeware',10);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (106,'Organic Yummy Tummy Maple & Brown Sugar Instant Oatmeal',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (107,'Mild Salsa Divino',51);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (108,'Organic Sprouted Barley Bread',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (109,'Grape Leaf Hummus Wrap',13);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (110,'Uncured Turkey Bologna',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (111,'Fabric Softener, Geranium Scent',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (112,'Hot Tomatillo Salsa',51);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (113,'Infant''s Blend Probiotic',70);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (114,'Light Savory Beef Barley Vegetable Soup',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (115,'Scooby-Doo! Fruit Flavored Snacks',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (116,'English Muffins',93);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (117,'Petit Suisse Fruit',2);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (118,'Ground Turkey Chub',34);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (119,'Chardonnay Paso Robles',62);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (120,'Cauliflower Florettes',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (121,'Sharp Cheddar',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (122,'Pomegranate Molasses',29);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (123,'Sherry Reserve Vinegar',19);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (124,'Sun Cups Dark Chocolate',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (125,'Herbal Armor DEET-Free Natural Insect Repellant',118);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (126,'Hot & Spicy Chicken Flavor Ramen Noodles',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (127,'Marscapone',108);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (128,'Organic Wild Blueberries',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (129,'Traditional Chicken & Orzo with Lemon Soup',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (130,'Vanilla Milk Chocolate Almond Ice Cream Bars Multi-Pack',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (131,'Brioche Bachelor Loaf',93);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (132,'Yogurt Strawberry Pomegranate',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (133,'Purifying Daily Detox Scrub',109);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (134,'Stain Release Boost In-Wash Stain Remover Pacs',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (135,'Dark Chocolate Ice Cream Topping',103);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (136,'Simple',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (137,'Very Vanilla Soymilk',91);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (138,'Olli Napoli Salami',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (139,'Zita Cut, No. 118',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (140,'Chips Onion Chipotle Garlic',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (141,'Restaurant Style Organic Chia & Quinoa Tortilla Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (142,'Arugula Salad',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (143,'Organic Lemons',24);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (144,'Coarse Grind Garlic Powder & Parsley Blend',104);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (145,'Traditional Water Crackers',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (146,'Anti Diarrheal Caplets',70);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (147,'Organic Ranch Veggie Dip',67);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (148,'Nectarines',24);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (149,'Wild Blueberry All Natural Fruit Spread',88);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (150,'Brut Rosé',134);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (151,'Aromatherapaes Stress Reducing Lavender & Chamomile Spa Bath',132);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (152,'3 in 1 Soap for Every Man, Cucumber & Lemon',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (153,'Fabric Refresher Meadows & Rain Air Freshener (1 Count, 27 oz)  Air Care',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (154,'Corn Dogs, Mini, Honey Crunchy Flavor',129);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (155,'Artisan Ciabatta',58);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (156,'Extra Spearmint Sugar-Free Gum',46);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (157,'Living Organic Cilantro',16);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (158,'Smoked Ham & Oven Roasted Turkey Sub Sandwich Kit',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (159,'Calcium Adult Gummy Vitamins, Orange Cherry & Strawberry',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (160,'100% Recycled Aluminum Foil',97);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (161,'Hacho Miso Aged & Fermented Soybeans',66);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (162,'Organic Mini Homestyle Waffles',52);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (163,'Dressing Bleu Cheese',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (164,'Peanut Butter Cacao Quinoa Clusters',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (165,'Wild Chanterelle Mushroom Ravioli',12);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (166,'Garlic Parmesan Pita Bread Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (167,'Sparkling Blush Grape Juice',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (168,'Halves & Pieces Walnuts',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (169,'Extra Sharp Cheddar Cheese',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (170,'Single Herbs Ginkgo Leaf Dietary Supplement',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (171,'Steakhouse Onion Burger with Garlic Seasoning',5);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (172,'Gluten Free All Natural Chocolate Chip Cookies',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (173,'Habanero Lime Shrimp Flavor Ramen Noodle Soup',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (174,'Vanishing Acne Treatment Cream',73);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (175,'T Bone Steak',122);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (176,'Original Turkey',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (177,'Citrus Terere Yerba Mate',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (178,'Vegan Santa Fe Style Flour Tortilla Rolled Tacos',42);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (179,'Penne Rigate With Spinach',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (180,'Simply Beyond Black Bean Tortilla Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (181,'Country Style Baked Beans',59);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (182,'Acti-Fresh Body Shape Long Unscented To Go Panty Liners',126);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (183,'Cookie Dough Performance Energy',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (184,'Kisses Milk Chocolate Candy',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (185,'Chicken Nugget Meal',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (186,'Fresh Scent Dishwasher Detergent with Dawn',74);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (187,'Wild Sardines in Marinara Sauce',95);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (188,'Mild El Nino Salsa',67);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (189,'Healthfull Nuts & Seeds Bread',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (190,'Classic Culinary Low Sodium Vegetable Broth',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (191,'Medium Spicy Butter Chicken Simmer Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (192,'Israeli Style Gefilte Fish',33);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (193,'fruitwater® Strawberry Kiwi Sparkling Water',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (194,'Lamb Rib Chops',122);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (195,'Grade A Pasteurized 2% Milkfat Lowfat Cottage Cheese with Pineapple',108);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (196,'Soda',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (197,'Cold Brew Coffee Tahitian Vanilla',26);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (198,'Tzatziki Cucumber Sauce',67);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (199,'Herb Thyme Clamshell',16);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (200,'Radiant Pantiliners Regular Wrapped Unscented',126);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (201,'Sloppy Joe',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (202,'Spinach & Feta Pierogi',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (203,'Rescue Remedy, Spray',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (204,'Free & Clear Natural Laundry Detergent For Sensitive Skin',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (205,'Chocolate Mint Cookie Crunch Nutrition Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (206,'Roasted Vegetable Soufflé',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (207,'Minis Candy Bars',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (208,'Vanilla Almond Cashew Almondmilk Cashewmilk Blend',91);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (209,'Italian Pasta Salad',1);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (210,'Homemade Hot Arrabbiata Fra Diavolo Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (211,'Gluten Free Organic Cereal Coconut Maple Vanilla',130);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (212,'Organic Blue Corn Sea Salt Tortilla Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (213,'Tapatio Salsa Picante Hot Sauce Tortilla Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (214,'Argan Oil of Morocco Renewing Weightless Healing Dry Oil Hair Oil',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (215,'Sambal Oelek Ground Fresh Chili Paste',66);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (216,'Gluten Free Oatmeal, Variety Pack',130);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (217,'String Cheese, Mozzarella',108);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (218,'6\" Organic Carrot Cake',8);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (219,'Totz Toothbrush Extra Soft 18+ Months',82);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (220,'Tegaderm Waterproof Transparent Dressing',118);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (221,'Cayenne Lemonade Made With Raw Tristate Honey',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (222,'Honey Nut Oatmeal Squares',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (223,'Kiwi Strawberry Sparkling Water',115);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (224,'Foaming Hand Soap Kid Watermelon',114);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (225,'3 Seed Blue Corn Dipping Chips',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (226,'Shaved Parmesan Cheese',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (227,'Triple Chocolate Snack Size',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (228,'Organic Soups Lentil',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (229,'EcoNet Recycled Bath Sponge',109);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (230,'Vanilla Cream Soda',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (231,'Low Sodium Turkey',49);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (232,'Blue Bottle Coffee Frozen Bar',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (233,'Chinese Breakfast Black Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (234,'Tennessee Whiskey',124);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (235,'Gluten Free Blueberry Muffin Mix',105);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (236,'Chicken Meatballs Dog Treats',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (237,'Brambleberry Herbal Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (238,'Alpha-Bits Multigrain Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (239,'Chicharrones Picante Flavor Pork Rinds',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (240,'Nature''s Seasons Seasoning Blend',104);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (241,'Shrimp with Pasta & Vegetables',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (242,'Original Red Twists',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (243,'Taco Reduced Sodium Seasoning Mix',5);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (244,'Organic Roasted Garlic Pasta Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (245,'Poppy Seed Bagels',93);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (246,'Triple-Acting Laundry Stain Remover',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (247,'Perfectly Thymed Pita Crisps Baked',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (248,'Dried Sweetened Cranberries',117);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (249,'Pinot Grigio, California, 2010',62);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (250,'Authentic Deep Dish, Spinach & Garlic Pizza',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (251,'Extra Strength Melatonin Adult Gummies',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (252,'Waffles, Red Berry',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (253,'Organic Vegetable Greens & Greens Juice Blend',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (254,'Honey Mustard',72);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (255,'Cold Remedy, Quick Dissolve Tablets, Cherry Flavor',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (256,'Island Fruits Fruit Snacks',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (257,'Key Lime Soda',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (258,'Vegetable Pot Pie',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (259,'Imported Italian Solid Light Tuna In Pure Olive Oil',95);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (260,'Cantaloupe',24);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (261,'Organic Southwestern Burrito',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (262,'Petite Dill Pickles',110);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (263,'Red Food Color',97);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (264,'Non-Fat Blueberry on the Bottom Greek Yogurt',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (265,'Glass Storage Container with Green Silicone Protection',85);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (266,'Rio Berry',64);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (267,'Triple Chocolate Ripple',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (268,'Sponge Mop',114);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (269,'Stuffed Crust Five Cheese Pizza',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (270,'OneZip Storage Bags Quart Size Value Pack',85);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (271,'TAI PEI      14OZ.SWEET & SOUR CHKN',38);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (272,'Propolis Herbal Supplement',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (273,'Thin Stackers Brown Rice  Salt Free',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (274,'Snack Bags',87);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (275,'Caramel Sauce',103);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (276,'French Vanilla Ice Cream',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (277,'Diet Root Beer',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (278,'Instant Mashed Potatoes',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (279,'Everyday Detox Dandelion Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (280,'Makeup Remover Cleansing Towelettes',73);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (281,'Chai Tea Bags',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (282,'Oh My Cod! Cod Pate and Vegetables Cat Food',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (283,'Organic Whole Wheat Elbows',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (284,'Organic Spicy Heirloom Marinara Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (285,'Mini Nilla Wafers Munch Pack',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (286,'Lite Poppy Seed Dressing Lite',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (287,'Turkey',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (288,'Original Sprouted Grains Protein & Fiber Hot Oatmeal',130);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (289,'100% Juice No Sugar Added Fruit Punch',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (290,'Organic Peppermint Lemonade',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (291,'Mint Dental Floss',20);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (292,'Fresh Multi-Purpose Contact Lens Solution',44);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (293,'Prime Filets Chicken & Tuna Dinner in Gravy Cat Food',41);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (294,'Minis Original Saltine Crackers',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (295,'Chewables Extra Strength Cherry Creme - 48 CT',70);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (296,'For Men Odor Armor Body Wash',127);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (297,'Write Bros Ball Point Pens, Cap-Pen, Medium (1.0 mm), Black Ink',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (298,'Brisk With Lemon Iced Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (299,'Organic Apple Spinach Kale Coconut Water Superjuice',98);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (300,'Organic Enriched Unbleached White Flour',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (301,'Biotin 10,000mcg Maximum Strength',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (302,'Gourmet Dog Treats Bone',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (303,'Candy, Original',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (304,'Dry Roasted Pistachios',117);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (305,'Wild Forest Raw Neem Honey',29);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (306,'Gold Potatoes',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (307,'Precious Mozzarella Cheese',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (308,'Advanced Haircare Color Vibrancy Nourishing Shampoo',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (309,'Graduates Lil'' Entrees Spiral Pasta In Turkey Meat Sauce With Green & Yellow Beans',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (310,'Crackers, Puffed, Corn, Quinoa & Sesame',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (311,'Naturals Savory Turkey Breakfast Sausage',52);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (312,'Juicing Carrots',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (313,'Peppermint/Banana Split Variety Pack Frozen Dairy Dessert Cones',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (314,'Extra Whitening Multi-Benefit Fluoride Toothpaste',20);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (315,'Creamy Italian Dressing Marinade',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (316,'Revive Anti-Perspirant Deodorant',80);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (317,'Best Grains Honey & Crunch Oat Bread',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (318,'Apple Cinnamon Crisp Candle',101);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (319,'Steamfresh Chef''s Favorites Lightly Sauced Roasted Red Potatoes & Green Beans',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (320,'Glycerine Soap, Pure and Natural, Cucumber',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (321,'Echinacea Goldenseal Alcohol Free Extract',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (322,'Brooklyn Pizza Dough',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (323,'Natural Food Color Packets',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (324,'Strong & Kind Roasted Jalapeno Almond Protein Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (325,'Veggie-Style Mini Corn Dogs',42);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (326,'Deluxe Sauce Made with 2% Milk Cheese Macaroni & Cheese Dinner',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (327,'Green Peas, Organic, Petite',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (328,'Disinfectant Spray Cherry Blossom & Pomegranate Scent',101);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (329,'Organic Whole Grassmilk Milk',84);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (330,'Chilpotles in Adobo Sauce',30);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (331,'Organic Lemon Gingersnap',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (332,'Raspberry Fig Bars',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (333,'Basil Daly Bar Soap',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (334,'Sparkling Raspberry Lemonade Water Beverage',115);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (335,'Blueberry Kombucha',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (336,'Black Currant Kombucha',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (337,'Soap, Pure-Castile, 18-in-1 Hemp, Lavender',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (338,'Yahrzeit Light Memorial Candle',33);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (339,'Creamline Yogurt Wild Blueberry',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (340,'Eco-Pac Kamut Puffs Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (341,'Cheese Creations Four Cheese Cheese Sauce',9);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (342,'Complete Health Deboned Chicken, Chicken Meal and Rice Cat Food',41);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (343,'Organic Whole Peeled Baby Carrots',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (344,'Lime Sherbet',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (345,'Extra Strength Berry',64);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (346,'Sunflower Bread',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (347,'Vegetable Salad Kit, Sweet Kale',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (348,'Super Slimming Herbal Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (349,'Organic Granulated Tapioca',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (350,'Mixed 12 Pack Lion''s Share Ale',27);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (351,'Go Fresh Nutrium Moisture Body Wash Blue Fig & Orange Blossom Scent',127);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (352,'Colby Jack & Mild Cheddar Combo Pack',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (353,'Tzatziki Greek Yogurt Dip',67);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (354,'Twist n Loc Small Round Containers + Lids',85);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (355,'Ground Flaxseed With Mixed Berries',117);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (356,'Ristorante Pizza Spinaci Thin Crust Pizza',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (357,'White Writing Gel',97);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (358,'Frozen All Butter Pound Cake',119);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (359,'Deli Thin-Sliced Honey Ham',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (360,'Whole Wheat Spanakopita',129);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (361,'Day and Night Multi-Symptom and Severe Cold & Cough Pain Reliever/Fever Reducer',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (362,'Pound Cake Cake Mix',105);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (363,'Water Crackers Original All Natural',78);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (364,'Greener Selection Salad',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (365,'Cheerios Cereal',121);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (366,'Vitamin C 1000 Mg Tropical Drink Mix Dietary Supplement',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (367,'Ultimate Omega 1000 mg Lemon Soft Gels',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (368,'Fabric Softener Dryer Sheet Free & Gentle 200CT Fabric Enhancers',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (369,'New Mexico Chili',30);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (370,'Chocolate Caramel Whey Protein Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (371,'Juniper Berry Soda',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (372,'Moisture Rich Sweet Orange & Argan Conditioner',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (373,'Honey Glazed Carrots',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (374,'Sliced Kosher Salami',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (375,'Multigrain Spaghetti Style Pasta',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (376,'Even & Bright Pink Lemon and Mandarin Orange Body Wash',127);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (377,'Chunky Beef with Vegetables & Brown Rice Dog Food',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (378,'Powerball Quantum Max Shine & Protect Automatic Dishwasher Detergent',74);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (379,'Super Dry Beer',27);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (380,'Clementine Bag',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (381,'Toaster Pops Strawberry',52);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (382,'Sugar Free Mint Patties',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (383,'Breaded Chicken Breast Tenders',34);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (384,'EverCurl Hydracharge Conditioner',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (385,'Liquid Drink Mix Blackberry Lemonade',90);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (386,'Real Chicken & Veggies Recipe Dog Food',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (387,'Chocolate Brownie Flavor Protein Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (388,'Stove Top Stuffing Mix for Turkey',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (389,'Mache Blend',123);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (390,'Super Enzymes',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (391,'Organic Yukon Gold Potato Bag',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (392,'OPA Greek Yogurt Ranch Dressing',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (393,'Phoenix Anti-Perspirant & Deodorant Stick Twin Pack',80);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (394,'Aquaphor Healing Ointment',127);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (395,'Sweet Cream Buttermilk Powder',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (396,'Cashews Natural Unsalted',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (397,'Pure Granulated Cane Sugar',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (398,'Organic Hard Candy Blood Orange and Honey',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (399,'Organic Strawberry Lemon-ade',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (400,'Grass-Fed Yogurt Blueberry Cardamom',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (401,'Flat Floss, Antiplaque, Naturally Waxed, Spearmint',20);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (402,'100% Pure Beef Homestyle Patties',34);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (403,'Ultra Thin Pastrami',96);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (404,'Reg; Organic Apple Cider Vinegar 16 Fl Oz',19);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (405,'100% Organic Diced Tomatoes',81);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (406,'Vanilla Almond Protein Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (407,'Almond Glow Almond Body Lotion/Massage Oil',109);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (408,'Pink Vitamin C 1000 Mg Pink Lemonade Drink Mix',47);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (409,'Original Bite Size Candies Natural & Artificial Flavors Fun Size',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (410,'Holiday Sugar Plum Spice Herbal Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (411,'Super Plus Cardboard Applicator Unscented Tampons',126);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (412,'Brazilian Keratin & Argan Oil Leave-In Conditioning & Styling Elixir',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (413,'Dual Action Beta Immune and Anti-Oxidant Effervescent Citrus',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (414,'Gluten Free Chicken Rustica Pizza',79);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (415,'16 oz Cold Cups',111);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (416,'Laundry Soil Stain Remover',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (417,'Classics Baby Binks Easter Chocolate Bunny',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (418,'Whole Grain Linguine Pasta',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (419,'Light & Fit Strawberry Cheesecake Greek Nonfat Yogurt',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (420,'International Cafe French Vanilla Mix',26);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (421,'Garlic & Herb Fresh Goat Cheese',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (422,'Mix-Up Flamin'' Hot & Cheezy Mix Flavored Snack Mix',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (423,'Red Jalapeno Caesar Dressing',89);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (424,'Linguine Pasta',131);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (425,'Sardines in Water Salt Added',33);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (426,'2nd Foods Bananas',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (427,'Italian Style Panko Breadcrumbs',5);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (428,'Everyday Mega Pack Paper Plates',111);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (429,'Dark Red Kidney Beans',59);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (430,'Born Yesterday Pale Ale',27);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (431,'Ice Cream, Cookies & Cream',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (432,'Vanilla Almond Breeze Almond Milk',91);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (433,'Organic Whole Granulation Roasted Buckwheat Groats',107);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (434,'Beach Sage Liquid Fabric Softener',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (435,'Dark Chocolate Raisins',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (436,'Petite Brussels Sprouts',116);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (437,'Strawberry Cheesecake Nonfat Yogurt',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (438,'Special K Vanilla Cappuccino Protein Breakfast Shakes',48);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (439,'Crispy Cinnamon Pear Chips',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (440,'Crossovers Olive Thyme Almond',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (441,'Antioxidant Cranberry Body Wash',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (442,'Sliced Chicken Entree Cat Food',41);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (443,'Ultra Power Plus Laundry Detergent 54 loads',75);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (444,'Special Recipe Italian Bread',112);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (445,'Almond Honey Protein+ Bar',3);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (446,'Blueberry Pomegranate Acaí Cultured Goat Milk Kefir',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (447,'Tea, Superflower, Hibiscus, Blueberry, Caffeine-Free, Bags',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (448,'White Chicken Chili',59);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (449,'Chips Ahoy! Chewy Cookies',61);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (450,'Chow Mein Thin Noodles',4);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (451,'Almond Spread, Dark Chocolate',88);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (452,'Sleepytime Sinus Soother Herbal Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (453,'Hummus Wrap',13);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (454,'Sloppy Joe Sauce',51);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (455,'Ibuprofen Liquid Gels',133);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (456,'Sparkling Blueberry',77);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (457,'Whole Wheat Fig Bar',48);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (458,'Total Advanced Floss Tip Medium Toothbrush',20);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (459,'Honey Vanilla Greek Yogurt',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (460,'Acai Dragonfruit Melon Green Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (461,'Sore Throat Wild Cherry Lozenges',11);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (462,'Fiber 4g Gummy Dietary Supplement',70);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (463,'Salt Free Seasoning',104);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (464,'Liquid Water Enhancer Peach Green Tea With Ginseng & Honey',90);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (465,'100% Natural Just Peaches',50);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (466,'Old Fashioned Vegetable Beef Soup',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (467,'Soup, Lower Sodium, Organic, Split Pea',69);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (468,'Kabocha Squash',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (469,'Whipping Cream',53);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (470,'Lite Beer',27);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (471,'Half ''n Half Lemonade Tea',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (472,'Fancy Diced Hot Chilies',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (473,'Plastic Measuring Cups',10);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (474,'Lavender Body Wash',25);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (475,'Organic Reposado Tequila',124);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (476,'Chub Mackerel',95);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (477,'Naturally Aged Cheddar Cheese Block Hot Habanero',21);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (478,'Organic Pitted Kalamata Olives',110);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (479,'Most Wanted Cabernet Sauvignon Red Wine',28);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (480,'Slow Churned Mint Chocolate Chip Ice Cream',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (481,'Black Peppercorns',104);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (482,'Gentle Clean Foaming Face Cleanser, 6.7 fl oz Female Skin Care',73);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (483,'\"Constant Comment\" Decaffeinated Black Tea Blend',94);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (484,'Plain Greek Goat Yogurt',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (485,'Country Stew Choice Cuts In Gravy Dog Food',40);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (486,'Lowfat Raspberry Kefir Probiotic Cultured Milk Smoothie',120);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (487,'Can/Bottle Opener, Chrome',10);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (488,'Organic Orange Turmeric Juice',31);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (489,'Dough for Turnover Pastries',58);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (490,'Gin Gins Candy',45);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (491,'Pompelmo Water',100);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (492,'Couscous, Israeli, Garlic Jalapeno',63);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (493,'Pear and Blueberry Baby Breakfast',92);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (494,'Yellow Cherry Tomato',83);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (495,'Pure Cane Granulated W/Spout Sugar',17);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (496,'Designer 9 Oz. Paper Cups',111);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (497,'Mascarpone Pistachio Caramel Gelato',37);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (498,'Daily Moisture Shampoo',22);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (499,'Aspirin 325 Mg',133);
INSERT INTO Product(Product_ID,Product_Name,Aisle_ID) VALUES (500,'Non-Scratch Scrub Sponges',114);
/*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*Inserts for Store*/
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('1 Rodgers Quay','Carrickfergus','Belfast','Co. Antrim','UK',02892508282);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('4 Braidwater Retail Park','Larne Road Link','Ballymena','Co. Antrim','UK',02892508283);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('5 Sprucefield Park','Lisburn','Lisburn','Co. Down','UK',02892508284);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('West Belfast Superstore','Unit 28, Kennedy Centre','Belfast','Co. Antrim','UK',02892508285);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Forestside Superstore','Forestside Shopping Centre, Upper Galwally','Belfast','Co. Antrim','UK',02892508286);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Craigavon Superstore','Rushmere Shopping Centre','Craigavon','Co. Armagh','UK',02892508287);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Holywood Exchange','302 Airport Road West','Belfast','Co. Antrim','UK',02892508288);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('10 Balloo Link','Bangor','Bangor','Co. Antrim','UK',02892508289);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('The Mall Shopping Centre','The Mall West','Armagh','Co. Armagh','UK',02892508290);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('The Quays','Newry','Newry','Co. Down','UK',02892508291);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('10 Riverside Regional Centre','Coleraine','Coleraine','Co. Antrim','UK',02892508292);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('150 Strand Road','Londonderry','Londonderry','Co. Londonderry','UK',02892508293);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Unit 14, The Oaks Centre','Oaks Road','Dungannon','Co. Tyrone','UK',02892508294);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Denton','Oldham Street','Manchester','Greater Manchester','UK',02892508295);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Manchester Piccadilly Local','Unit 1','Manchester','Greater Manchester','UK',02892508296);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Manchester Oxford Road Local','Horniman House','Manchester','Greater Manchester','UK',02892508297);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Manchester Station Approach Local','111 Piccadilly','Manchester','Greater Manchester','UK',02892508298);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Mosley Streey Local','58 Mosley Street','Manchester','Greater Manchester','UK',02892508299);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Whitworth Street Local','51 Whitworth Street West','Manchester','Greater Manchester','UK',02892508300);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Fallowfield','347 Wilmslow Road','Manchester','Greater Manchester','UK',02892508301);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Cross Street Local','22 Cross Street','Manchester','Greater Manchester','UK',02892508302);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Manchester First Street','Isabella Banks Street','Manchester','Greater Manchester','UK',02892508303);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Deansgate','130 Deansgate','Manchester','Greater Manchester','UK',02892508304);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Greengate','1c Greengate','Salford','Greater Manchester','UK',02892508305);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Overseas House','Overseas House','Manchester','Greater Manchester','UK',02892508306);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Ashton Moss','2 Lord Sheldon Way','Ashton-Under-Lyne','Greater Manchester','UK',02892508307);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Withington Local','496 Wilmslow Road','Manchester','Greater Manchester','UK',02892508308);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Salford','100 Regent Road','Salford','Greater Manchester','UK',02892508309);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Stockport','Warren Street','Stockport','Greater Manchester','UK',02892508310);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Salford Harbour City','Uni 1 Michigan Tower','Manchester','Greater Manchester','UK',02892508311);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Sedgley Park Local','25 Bury New Road','Manchester','Greater Manchester','UK',02892508312);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Heaton Park','Heaton Park Road','Manchester','Greater Manchester','UK',02892508313);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Oldam','60 Union Street','Oldam','Greater Manchester','UK',02892508314);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Romiley Local','2 Compstall Road','Stockport','Greater Manchester','UK',02892508315);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Cheadle Warwick Mall Local','39 High Street','Cheadle','Greater Manchester','UK',02892508316);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Eccles Gilda Brook Road','110 Gilda Brook Road','Manchester','Greater Manchester','UK',02892508317);
INSERT INTO Addresses(AD1,AD2,City_Town,District,Country,Telephone_No) VALUES ('Hazel Grove','London Road','Stockport','Greater Manchester','UK',02892508318);
/*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*Inserts for Store*/
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (1,'Carrickfergus Superstore','Carrickfergus');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (2,'Ballymena Superstore','Larne Road Link');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (3,'Sprucefield Superstore','Lisburn');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (4,'West Belfast Superstore','Unit 28, Kennedy Centre');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (5,'Forestside Superstore','Forestside Shopping Centre, Upper Galwally');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (6,'Craigavon Superstore','Rushmere Shopping Centre');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (7,'Holywood Exchange Superstore','302 Airport Road West');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (8,'Bangor Superstore','Bangor');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (9,'Armagh Superstore','The Mall West');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (10,'Newry Superstore','Newry');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (11,'Coleraine Superstore','Coleraine');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (12,'Strand Road Superstore','Londonderry');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (13,'Dungannon Superstore','Oaks Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (14,'Denton Store','Oldham Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (15,'Manchester Piccadilly Local','Unit 1');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (16,'Manchester Oxford Road Local','Horniman House');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (17,'Manchester Station Approach Local','111 Piccadilly');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (18,'Mosley Streey Local','58 Mosley Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (19,'Whitworth Street Local','51 Whitworth Street West');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (20,'Fallowfield Store','347 Wilmslow Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (21,'Cross Street Local','22 Cross Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (22,'Manchester First Street Store','Isabella Banks Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (23,'Deansgate Super','130 Deansgate');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (24,'Greengate Store','1c Greengate');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (25,'Overseas House Store','Overseas House');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (26,'Ashton Moss Store','2 Lord Sheldon Way');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (27,'Withington Local','496 Wilmslow Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (28,'Salford Store','100 Regent Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (29,'Stockport Store','Warren Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (30,'Salford Harbour City Store','Uni 1 Michigan Tower');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (31,'Sedgley Park Local','25 Bury New Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (32,'Heaton Park Store','Heaton Park Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (33,'Oldam Store','60 Union Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (34,'Romiley Local','2 Compstall Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (35,'Cheadle Warwick Mall Local','39 High Street');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (36,'Eccles Gilda Brook Road Store','110 Gilda Brook Road');
INSERT INTO Store(Store_ID,Store_Name,Address) VALUES (37,'Hazel Grove Store','London Road');


